# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XrdXFJ90k25UZqNty_7QiA8r5_D1jp8H
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

"""# New section"""

import pandas as pd
df = pd.read_csv("police_department_data.csv")
df.head(5)

df['department_district'].value_counts()
type(df['department_district'].value_counts())
df_crime = df['department_district'].value_counts().reset_index()
df_crime.columns = ['Neighbourhood', 'Count']
df_crime

!conda install -c conda-forge folium=0.5.0 --yes
import folium
print('Folium installed and imported')
gjson = r'https://cocl.us/sanfran_geojson'
latitude = 37.77
longitude = -122.42
Sanfran_map = folium.Map(location=[latitude, longitude], zoom_start=12)
Sanfran_map.choropleth(
    geo_data=gjson,
    data=df_crime,
    columns=['Neighbourhood', 'Count'],
    key_on='feature.properties.DISTRICT',
    fill_color='YlOrRd',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Crime Rate In San Francisco')
Sanfran_map